name: 'Deploy to Netlify'

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        run: |
          mkdir ./bin
          curl -SLo - https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.tar.gz | tar xz -C ./bin

      - name: Build
        run: ./bin/hugo --debug --minify -b 'https://www.thelonelyghost.com'

      - name: Deploy
        uses: jsmrcaga/action-netlify-deploy@v1.1.0
        with:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
          NETLIFY_DEPLOY_MESSAGE: "Prod deploy ${{ github.ref }}"
          NETLIFY_DEPLOY_TO_PROD: true
          build_directory: 'public'
