name: 'Deploy to Netlify'

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        run: |
          mkdir ./bin
          curl -SLo - https://github.com/gohugoio/hugo/releases/download/v0.74.3/hugo_extended_0.74.3_Linux-64bit.tar.gz | tar xz -C ./bin
          ./bin/hugo version

      - name: Setup Netlify CLI
        run: |
          npm install
          ./node_modules/.bin/netlify --version

      - name: Build
        run: ./bin/hugo --debug --minify -b 'https://www.thelonelyghost.com'

      - name: Deploy
        run: ./node_modules/.bin/netlify deploy --auth '${{ secrets.NETLIFY_TOKEN }}' --site '${{ secrets.NETLIFY_SITE_ID }}' --message 'Prod deployment via GitHub Actions (${{ github.sha }})' --dir 'public' --prod
